[package]
name = "funkshunl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.regex]
version = "1.3.0"
default-features = false
features = ["std"]
